/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronTelegramReportRouteImport } from './routes/api/public/cron/telegram-report'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronTelegramReportRoute =
  ApiPublicCronTelegramReportRouteImport.update({
    id: '/api/public/cron/telegram-report',
    path: '/api/public/cron/telegram-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/stats': typeof StatsRoute
  '/api/public/cron/telegram-report': typeof ApiPublicCronTelegramReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/stats': typeof StatsRoute
  '/api/public/cron/telegram-report': typeof ApiPublicCronTelegramReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/stats': typeof StatsRoute
  '/api/public/cron/telegram-report': typeof ApiPublicCronTelegramReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/stats' | '/api/public/cron/telegram-report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/stats' | '/api/public/cron/telegram-report'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/stats'
    | '/api/public/cron/telegram-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StatsRoute: typeof StatsRoute
  ApiPublicCronTelegramReportRoute: typeof ApiPublicCronTelegramReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/telegram-report': {
      id: '/api/public/cron/telegram-report'
      path: '/api/public/cron/telegram-report'
      fullPath: '/api/public/cron/telegram-report'
      preLoaderRoute: typeof ApiPublicCronTelegramReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StatsRoute: StatsRoute,
  ApiPublicCronTelegramReportRoute: ApiPublicCronTelegramReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
